version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: root

  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql:/etc/mysql
      - ./data/mysql:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root